language: ruby
cache:
- bundler
before_install:
  gem install bundler -v 1.15
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - myself@cflee.net
    on_success: change
    on_failure: always
script:
  - gem build sensu-plugins-chage.gemspec
  - gem install sensu-plugins-chage-*.gem
  - bundle exec rake default
deploy:
  provider: rubygems
  api_key:
    secure: <encrypted rubygems deploy key>
  gem: sensu-plugins-chage
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-chage
